//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Typeid { get; set; }
        public Nullable<int> StatusId { get; set; }
        public int OrganizationId { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string PurchasedBy { get; set; }
        public string SerialNo { get; set; }
        public string AssetTag { get; set; }
        public Nullable<int> ManufacturerId { get; set; }
        public string Model { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public string InstalledBy { get; set; }
        public string PhysicalPosition { get; set; }
        public string Hostname { get; set; }
        public string PrimaryIP { get; set; }
        public string MacAddress { get; set; }
        public string DefaultGateway { get; set; }
        public Nullable<int> PlatformId { get; set; }
        public Nullable<int> OperatingSystemId { get; set; }
        public string OperatingSystemNotes { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> AccesstoAll { get; set; }
        public Nullable<long> DataSourceId { get; set; }
        public string DataSourceType { get; set; }
    }
}
