//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactLocation
    {
        public int ContactLocationId { get; set; }
        public Nullable<System.Guid> TenantID { get; set; }
        public string ContactLocationName { get; set; }
    }
}
