//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactEmail
    {
        public int ContactEmailId { get; set; }
        public Nullable<int> ContactId { get; set; }
        public int EmailTypeId { get; set; }
        public string Email { get; set; }
        public Nullable<bool> isPrimaryEmail { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual ContactEmailType ContactEmailType { get; set; }
    }
}
