//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Password
    {
        public int ID { get; set; }
        public int OrganizationId { get; set; }
        public Nullable<int> AssetType { get; set; }
        public Nullable<int> AssetId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Description { get; set; }
        public string UserName { get; set; }
        public string Password1 { get; set; }
        public Nullable<System.DateTime> PasswordChangeDate { get; set; }
        public Nullable<bool> IsEmbedded { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string URL { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> AccessToAll { get; set; }
    
        public virtual PasswordCategory PasswordCategory { get; set; }
    }
}
