//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPlan
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string IconImagepath { get; set; }
        public decimal BasePrice { get; set; }
        public Nullable<int> Includedusers { get; set; }
        public decimal AdditionalUserRate { get; set; }
        public Nullable<bool> TrialPlan { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> Organizations { get; set; }
        public Nullable<int> UsersPerOrg { get; set; }
        public Nullable<int> DataSources { get; set; }
        public Nullable<decimal> AdditionalOrgRate { get; set; }
        public Nullable<bool> AllowWhiteLabeling { get; set; }
        public Nullable<bool> AllowAccountManager { get; set; }
        public Nullable<bool> AllowSupport { get; set; }
        public Nullable<bool> AllowAccessAudit { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<long> StripePlanId { get; set; }
        public Nullable<bool> AllowBasecamp { get; set; }
        public Nullable<bool> AllowChatSupport { get; set; }
    }
}
