//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenantCardInfo
    {
        public int ID { get; set; }
        public System.Guid TenantId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CardNo { get; set; }
        public string SecurityCode { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<byte> CardType { get; set; }
        public bool Active { get; set; }
    }
}
