//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenant
    {
        public int ID { get; set; }
        public System.Guid TenantId { get; set; }
        public string CompanyName { get; set; }
        public string SubDomain { get; set; }
        public int PlanId { get; set; }
        public string EmailId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public byte Status { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Userlicense { get; set; }
        public Nullable<int> Organizations { get; set; }
        public Nullable<int> UsersPerOrg { get; set; }
        public Nullable<int> DataSources { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
        public Nullable<decimal> ServiceTax { get; set; }
        public Nullable<decimal> ExtraCharges { get; set; }
        public Nullable<System.DateTime> RenewalDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<bool> IsTrial { get; set; }
        public string CompanyLogo { get; set; }
        public Nullable<int> Includedusers { get; set; }
        public Nullable<decimal> AdditionalUserRate { get; set; }
        public Nullable<decimal> AdditionalOrgRate { get; set; }
        public Nullable<bool> AllowWhiteLabeling { get; set; }
        public Nullable<bool> AllowAccountManager { get; set; }
        public Nullable<bool> AllowSupport { get; set; }
        public Nullable<bool> AllowAccessAudit { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string StripeCustId { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public string StripeChargeId { get; set; }
        public string StripeBalanceTransactionId { get; set; }
        public Nullable<bool> TransactionSuccess { get; set; }
        public Nullable<bool> AllowBasecamp { get; set; }
        public Nullable<bool> AllowChatSupport { get; set; }
    }
}
